---
title: Platypodes.xyz
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: A place for the things I do
baseurl: ''
url: ''
github_username: platypodeCode
markdown: kramdown
